### PR TITLE
Swift Mailer support

### PR DESCRIPTION
**Pull request by Jacquesvw**
I made changes to phpBMS to support the latest Swift Mailer 4.1.5 and i think it's a much better solution than the old mail() function from PHP originally used to send invoices and quotes. I wanted to use PHP Mailer, but it's a dead project and I found some problems with it being outdated and not properly "talking" to some mail servers.

In this fork phpBMS now support SMTP, Sendmail and Mail.

The mail settings can be altered in the user's account.

Regards,
Jacques

### CODE REVIEW

**Comment by weex** [comment]
Thanks Jacquesvw so much for this huge contribution. I'm testing this out now. One thing I'm concerned about for the future is keeping these libraries (Swift Mailer and FPDF) updated while preserving any customizations for phpBMS. I'll check through the commits of course but did you make any changes to the above libraries? Also with the FPDF stuff did you check if any previous customizations where made to 1.4.2 or whatever version was in there?

**Comment by Jacquesvw** [comment]
I made no changes to the Swift Mailer libraries, so updating to a new version in the future is simply a matter of copying the new version into the swift-mailer folder.

There were custom functions added to FPDI, but when I updated to the latest version I made sure to include those as well. I've been testing out the PDF creation and so far nothing seems to be broken.

**Comment by weex** [comment]
Hello, Do you have any plans to fix/test this in the near future? Others are forking the code and I do think it would be great for everyone to move forward with your Swiftmailer patch.

**Comment by Jacquesvw** [comment]
Yes, I should get around to fixing it today. I also added the ability to print payment instructions to quotes and will upload that code today or tomorrow as well.

**Comment by Jacquesvw** [comment]
Hi D,

I fixed the installer so that clean installs work properly now and I also fixed the updater so that updating from v0.98 works. The update was tested using a clean install of version 0.98 that I downloaded at www.phpbms.org and it worked fine.

**Pull request merged**
